#!/bin/bash
# filepath: zfs-pre-checks.sh
# ZFS Pre-Update Checks for Void Linux with ZFSBootMenu Support
# This script checks for updates FIRST, then performs comprehensive system checks

set -euo pipefail

# Configuration
LOG_FILE="/var/log/zfs-pre-checks-$(date +%Y%m%d-%H%M%S).log"
BACKUP_DIR="/var/backups/zfs-update-$(date +%Y%m%d-%H%M%S)"
CONFIG_FILE="/etc/zfs-update.conf"
ZBM_CONFIG="/etc/zfsbootmenu/config.yaml"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

log() {
    echo -e "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

success() {
    log "${GREEN}✓ $1${NC}"
}

warning() {
    log "${YELLOW}⚠ WARNING: $1${NC}"
}

error() {
    log "${RED}✗ ERROR: $1${NC}"
}

info() {
    log "${BLUE}ℹ INFO: $1${NC}"
}

header() {
    echo ""
    log "${BOLD}${CYAN}=========================================="
    log "$1"
    log "==========================================${NC}"
    echo ""
}

error_exit() {
    error "$1"
    log "Pre-checks failed. Fix issues before proceeding with updates."
    exit 1
}

check_root() {
    if [ "$EUID" -ne 0 ]; then
        error_exit "This script must be run as root"
    fi
}

create_initial_config() {
    cat > "$CONFIG_FILE" << EOF
# ZFS Update Configuration
# Generated by zfs-pre-checks.sh on $(date)
BACKUP_DIR="$BACKUP_DIR"
LOG_FILE="$LOG_FILE"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
SCRIPT_VERSION="1.0"
EOF
    chmod 600 "$CONFIG_FILE"
}

check_available_updates() {
    header "CHECKING FOR AVAILABLE UPDATES"
    
    info "Syncing package database..."
    if ! xbps-install -S; then
        error_exit "Failed to sync package database. Check network connection."
    fi
    success "Package database synced"
    
    # Check for ZFS updates
    ZFS_UPDATES=$(xbps-install -un 2>/dev/null | grep "zfs" || true)
    ZFS_COUNT=$(echo "$ZFS_UPDATES" | grep -c "zfs" || echo "0")
    
    # Check for kernel updates
    KERNEL_UPDATES=$(xbps-install -un 2>/dev/null | grep -E "linux[0-9]*-[0-9]" || true)
    KERNEL_COUNT=$(echo "$KERNEL_UPDATES" | grep -c -E "linux[0-9]*-[0-9]" || echo "0")
    
    # Check for firmware updates
    FIRMWARE_UPDATES=$(xbps-install -un 2>/dev/null | grep "linux-firmware" || true)
    FIRMWARE_COUNT=$(echo "$FIRMWARE_UPDATES" | grep -c "linux-firmware" || echo "0")
    
    # Log findings
    info "Update availability results:"
    log "  ZFS updates: $ZFS_COUNT packages"
    log "  Kernel updates: $KERNEL_COUNT packages"
    log "  Firmware updates: $FIRMWARE_COUNT packages"
    
    # Show detailed update information
    if [ -n "$ZFS_UPDATES" ]; then
        info "ZFS updates available:"
        echo "$ZFS_UPDATES" | while IFS= read -r line; do
            [ -n "$line" ] && log "  $line"
        done
    fi
    
    if [ -n "$KERNEL_UPDATES" ]; then
        info "Kernel updates available:"
        echo "$KERNEL_UPDATES" | while IFS= read -r line; do
            [ -n "$line" ] && log "  $line"
        done
    fi
    
    if [ -n "$FIRMWARE_UPDATES" ]; then
        info "Firmware updates available:"
        echo "$FIRMWARE_UPDATES" | while IFS= read -r line; do
            [ -n "$line" ] && log "  $line"
        done
    fi
    
    # Determine if we have any relevant updates
    TOTAL_UPDATES=$((ZFS_COUNT + KERNEL_COUNT + FIRMWARE_COUNT))
    
    if [ "$TOTAL_UPDATES" -eq 0 ]; then
        header "NO UPDATES AVAILABLE"
        success "System is up to date for ZFS-related packages"
        info "You can run 'xbps-install -u' to check for other package updates"
        
        # Create minimal config for consistency
        {
            echo "UPDATES_AVAILABLE=false"
            echo "TOTAL_UPDATES=0"
            echo "ZFS_COUNT=0"
            echo "KERNEL_COUNT=0"
            echo "FIRMWARE_COUNT=0"
        } >> "$CONFIG_FILE"
        
        return 1  # No updates needed
    else
        success "Found $TOTAL_UPDATES ZFS/kernel/firmware updates"
        
        # Save update information to config
        {
            echo "UPDATES_AVAILABLE=true"
            echo "TOTAL_UPDATES=$TOTAL_UPDATES"
            echo "ZFS_COUNT=$ZFS_COUNT"
            echo "KERNEL_COUNT=$KERNEL_COUNT"
            echo "FIRMWARE_COUNT=$FIRMWARE_COUNT"
        } >> "$CONFIG_FILE"
        
        return 0  # Updates available
    fi
}

check_zfs_loaded() {
    info "Checking ZFS module status..."
    
    if ! lsmod | grep -q zfs; then
        error_exit "ZFS module is not loaded. Load it with: modprobe zfs"
    fi
    
    if ! command -v zpool >/dev/null 2>&1; then
        error_exit "ZFS userland tools not found. Install zfs package."
    fi
    
    if ! command -v zfs >/dev/null 2>&1; then
        error_exit "ZFS userland tools not found. Install zfs package."
    fi
    
    success "ZFS module and tools are available"
}

detect_zfsbootmenu() {
    info "Detecting boot method..."
    
    ZBM_DETECTED=false
    
    # Multiple detection methods
    if [ -f "$ZBM_CONFIG" ]; then
        ZBM_DETECTED=true
        info "ZFSBootMenu configuration found: $ZBM_CONFIG"
    fi
    
    if command -v efibootmgr >/dev/null 2>&1; then
        if efibootmgr 2>/dev/null | grep -qi "zfsbootmenu\|zbm"; then
            ZBM_DETECTED=true
            info "ZFSBootMenu found in EFI boot entries"
        fi
    fi
    
    if grep -q "zfsbootmenu" /proc/cmdline 2>/dev/null; then
        ZBM_DETECTED=true
        info "ZFSBootMenu detected in current boot parameters"
    fi
    
    if command -v zfsbootmenu >/dev/null 2>&1; then
        ZBM_DETECTED=true
        ZBM_VERSION=$(zfsbootmenu --version 2>/dev/null || echo "unknown")
        info "ZFSBootMenu command available, version: $ZBM_VERSION"
    fi
    
    if [ "$ZBM_DETECTED" = true ]; then
        success "ZFSBootMenu system detected"
        echo "ZFSBOOTMENU=true" >> "$CONFIG_FILE"
    else
        info "Traditional bootloader system (GRUB/systemd-boot)"
        echo "ZFSBOOTMENU=false" >> "$CONFIG_FILE"
    fi
}

check_system_versions() {
    info "Checking current system versions..."
    
    CURRENT_KERNEL=$(uname -r)
    CURRENT_ZFS=$(modinfo zfs 2>/dev/null | grep -E "^version:" | awk '{print $2}' || echo "unknown")
    ZFS_USERLAND=$(zfs version 2>/dev/null | head -1 | awk '{print $2}' || echo "unknown")
    
    log "Current kernel: $CURRENT_KERNEL"
    log "ZFS kernel module: $CURRENT_ZFS"
    log "ZFS userland: $ZFS_USERLAND"
    
    # Check for version mismatch
    if [ "$CURRENT_ZFS" != "unknown" ] && [ "$ZFS_USERLAND" != "unknown" ] && [ "$CURRENT_ZFS" != "$ZFS_USERLAND" ]; then
        warning "ZFS kernel module ($CURRENT_ZFS) and userland ($ZFS_USERLAND) versions differ"
        warning "This is normal if updates are available"
    else
        success "ZFS kernel and userland versions match"
    fi
    
    # Save version info
    {
        echo "CURRENT_KERNEL=\"$CURRENT_KERNEL\""
        echo "CURRENT_ZFS=\"$CURRENT_ZFS\""
        echo "ZFS_USERLAND=\"$ZFS_USERLAND\""
    } >> "$CONFIG_FILE"
}

check_pool_health() {
    info "Checking ZFS pool health..."
    
    if ! zpool list >/dev/null 2>&1; then
        warning "No ZFS pools found"
        echo "POOLS_EXIST=false" >> "$CONFIG_FILE"
        return 0
    fi
    
    echo "POOLS_EXIST=true" >> "$CONFIG_FILE"
    
    info "Current pool status:"
    zpool status -v | tee -a "$LOG_FILE"
    
    if zpool status | grep -E "(DEGRADED|FAULTED|OFFLINE|UNAVAIL)"; then
        error_exit "ZFS pools have errors. Fix pool issues before updating."
    fi
    
    if zpool status | grep -q "scrub in progress"; then
        error_exit "ZFS scrub is in progress. Wait for completion before updating."
    fi
    
    if zpool status | grep -q "resilver in progress"; then
        error_exit "ZFS resilver is in progress. Wait for completion before updating."
    fi
    
    success "All ZFS pools are healthy"
}

check_zbm_boot_pool() {
    if [ "$ZBM_DETECTED" != true ]; then
        return 0
    fi
    
    info "Checking ZFSBootMenu boot pool configuration..."
    
    # Find boot pools
    BOOT_POOLS=$(zpool list -H -o name 2>/dev/null | grep -E "(bpool|boot)" || true)
    
    if [ -z "$BOOT_POOLS" ] && [ -f "$ZBM_CONFIG" ]; then
        # Try to detect from ZBM config
        BOOT_POOLS=$(grep -E "pool:" "$ZBM_CONFIG" 2>/dev/null | grep -v "^#" | awk -F: '{print $2}' | tr -d ' "' || true)
    fi
    
    if [ -n "$BOOT_POOLS" ]; then
        info "Boot pool(s) detected: $BOOT_POOLS"
        echo "BOOT_POOLS=\"$BOOT_POOLS\"" >> "$CONFIG_FILE"
        
        for pool in $BOOT_POOLS; do
            if ! zpool status "$pool" | grep -q "state: ONLINE"; then
                error_exit "Boot pool $pool is not ONLINE. Fix before updating."
            fi
        done
        
        success "Boot pool(s) are healthy"
    else
        warning "No dedicated boot pool found"
        echo "BOOT_POOLS=\"\"" >> "$CONFIG_FILE"
    fi
}

check_zbm_esp() {
    if [ "$ZBM_DETECTED" != true ]; then
        return 0
    fi
    
    info "Checking EFI System Partition for ZFSBootMenu..."
    
    ESP_MOUNT=$(findmnt -n -o TARGET -t vfat 2>/dev/null | head -1 || echo "/boot/efi")
    
    if [ ! -d "$ESP_MOUNT" ]; then
        error_exit "EFI System Partition not found. ZFSBootMenu requires ESP."
    fi
    
    ESP_USAGE=$(df "$ESP_MOUNT" | awk 'NR==2 {print $5}' | sed 's/%//')
    ESP_FREE_MB=$(df -m "$ESP_MOUNT" | awk 'NR==2 {print $4}')
    
    if [ "$ESP_USAGE" -gt 80 ]; then
        warning "EFI System Partition is ${ESP_USAGE}% full"
    fi
    
    if [ "$ESP_FREE_MB" -lt 50 ]; then
        error_exit "EFI System Partition has less than 50MB free"
    fi
    
    # Check for ZBM files
    if [ -f "$ESP_MOUNT/EFI/zbm/vmlinuz.efi" ]; then
        ZBM_EFI_PATH="$ESP_MOUNT/EFI/zbm/vmlinuz.efi"
        echo "ZBM_EFI_PATH=\"$ZBM_EFI_PATH\"" >> "$CONFIG_FILE"
        success "ZFSBootMenu EFI image found"
    fi
    
    {
        echo "ESP_MOUNT=\"$ESP_MOUNT\""
        echo "ESP_USAGE=$ESP_USAGE"
        echo "ESP_FREE_MB=$ESP_FREE_MB"
    } >> "$CONFIG_FILE"
    
    success "ESP check completed (${ESP_USAGE}% used, ${ESP_FREE_MB}MB free)"
}

check_disk_space() {
    info "Checking disk space..."
    
    ROOT_USAGE=$(df / | awk 'NR==2 {print $5}' | sed 's/%//')
    ROOT_FREE_MB=$(df -m / | awk 'NR==2 {print $4}')
    
    if [ "$ROOT_USAGE" -gt 90 ]; then
        error_exit "Root filesystem is ${ROOT_USAGE}% full. Need space for updates."
    fi
    
    if mountpoint -q /boot 2>/dev/null; then
        BOOT_USAGE=$(df /boot | awk 'NR==2 {print $5}' | sed 's/%//')
        BOOT_FREE_MB=$(df -m /boot | awk 'NR==2 {print $4}')
        
        if [ "$BOOT_USAGE" -gt 80 ]; then
            warning "Boot partition is ${BOOT_USAGE}% full"
        fi
        
        if [ "$BOOT_FREE_MB" -lt 100 ]; then
            error_exit "Boot partition needs at least 100MB free"
        fi
    fi
    
    BACKUP_FREE_MB=$(df -m "$(dirname "$BACKUP_DIR")" | awk 'NR==2 {print $4}')
    if [ "$BACKUP_FREE_MB" -lt 1024 ]; then
        warning "Less than 1GB available for backups"
    fi
    
    success "Sufficient disk space available"
}

check_running_processes() {
    info "Checking for interfering processes..."
    
    # Check for database processes
    if pgrep -f "(mysqld|postgresql|mongodb|mariadb)" >/dev/null 2>&1; then
        warning "Database processes detected - consider stopping before update"
    fi
    
    # Check for backup processes
    if pgrep -f "(rsync|borgbackup|duplicity)" >/dev/null 2>&1; then
        warning "Backup processes detected - consider waiting for completion"
    fi
    
    success "Process check completed"
}

create_backups() {
    info "Creating backup directory and configurations..."
    
    mkdir -p "$BACKUP_DIR"
    
    if [ "${POOLS_EXIST:-false}" = "true" ]; then
        info "Backing up ZFS configurations..."
        {
            zfs list -H -o name,mountpoint > "$BACKUP_DIR/zfs-datasets.txt"
            zpool list -H > "$BACKUP_DIR/zpool-list.txt"
            zfs get all > "$BACKUP_DIR/zfs-properties.txt"
            zpool get all > "$BACKUP_DIR/zpool-properties.txt"
        } 2>/dev/null || warning "Some ZFS backup commands failed"
    fi
    
    # Backup system configs
    cp /etc/fstab "$BACKUP_DIR/" 2>/dev/null || true
    
    if [ -d /boot/grub ]; then
        cp -r /boot/grub "$BACKUP_DIR/grub-backup/" 2>/dev/null || true
    fi
    
    if [ -f /etc/dracut.conf ]; then
        cp /etc/dracut.conf "$BACKUP_DIR/" 2>/dev/null || true
    fi
    
    if [ -d /etc/dracut.conf.d ]; then
        cp -r /etc/dracut.conf.d "$BACKUP_DIR/" 2>/dev/null || true
    fi
    
    success "System configuration backup created"
}

backup_zbm_configuration() {
    if [ "$ZBM_DETECTED" != true ]; then
        return 0
    fi
    
    info "Backing up ZFSBootMenu configuration..."
    
    if [ -f "$ZBM_CONFIG" ]; then
        cp "$ZBM_CONFIG" "$BACKUP_DIR/zfsbootmenu-config.yaml" 2>/dev/null || true
    fi
    
    if [ -d "/etc/zfsbootmenu" ]; then
        cp -r "/etc/zfsbootmenu" "$BACKUP_DIR/zfsbootmenu-etc/" 2>/dev/null || true
    fi
    
    if [ -n "${ZBM_EFI_PATH:-}" ] && [ -f "$ZBM_EFI_PATH" ]; then
        cp "$ZBM_EFI_PATH" "$BACKUP_DIR/vmlinuz.efi.backup" 2>/dev/null || true
    fi
    
    if command -v efibootmgr >/dev/null 2>&1; then
        efibootmgr -v > "$BACKUP_DIR/efi-boot-entries.txt" 2>&1 || true
    fi
    
    success "ZFSBootMenu configuration backed up"
}

# Add this after backup_zbm_configuration() function:

backup_esp_completely() {
    if [ "$ZFSBOOTMENU" != true ]; then
        return 0
    fi
    
    info "Creating complete ESP backup..."
    
    ESP_MOUNT=${ESP_MOUNT:-/boot/efi}
    
    if [ ! -d "$ESP_MOUNT" ]; then
        warning "ESP mount point not found: $ESP_MOUNT"
        return 0
    fi
    
    # Create ESP backup directory
    ESP_BACKUP_DIR="$BACKUP_DIR/esp-complete-backup"
    mkdir -p "$ESP_BACKUP_DIR"
    
    # Backup entire ESP structure
    if cp -r "$ESP_MOUNT"/* "$ESP_BACKUP_DIR/" 2>/dev/null; then
        success "Complete ESP backup created"
    else
        warning "ESP backup may be incomplete"
    fi
    
    # Get partition information
    {
        echo "=== ESP Filesystem Info ==="
        df -h "$ESP_MOUNT" 2>/dev/null || true
        echo ""
        echo "=== ESP Mount Info ==="
        findmnt "$ESP_MOUNT" 2>/dev/null || true
        echo ""
        echo "=== ESP Contents ==="
        find "$ESP_MOUNT" -type f 2>/dev/null || true
    } > "$BACKUP_DIR/esp-info.txt"
    
    success "ESP information saved to esp-info.txt"
}

main() {
    header "ZFS PRE-UPDATE CHECKS"
    
    log "Starting ZFS pre-update checks..."
    
    check_root
    create_initial_config
    
    # CRITICAL: Check for updates FIRST
    if ! check_available_updates; then
        # No updates available - clean exit
        exit 0
    fi
    
    # Updates available - continue with full checks
    header "UPDATES FOUND - PERFORMING SYSTEM CHECKS"
    
    check_zfs_loaded
    detect_zfsbootmenu
    check_system_versions
    check_pool_health
    check_zbm_boot_pool
    check_zbm_esp
    check_disk_space
    check_running_processes
    create_backups
    backup_zbm_configuration
	backup_esp_completely
    
    header "PRE-CHECKS COMPLETED SUCCESSFULLY"
    
    success "All pre-update checks passed!"
    log "System type: $([ "$ZBM_DETECTED" = true ] && echo "ZFSBootMenu" || echo "Traditional")"
    log "Updates found: ${TOTAL_UPDATES} packages (ZFS: ${ZFS_COUNT}, Kernel: ${KERNEL_COUNT}, Firmware: ${FIRMWARE_COUNT})"
    log "Backup directory: $BACKUP_DIR"
    log "Configuration saved to: $CONFIG_FILE"
    log "Ready to proceed with updates"
    
    echo ""
    echo "=========================================="
    echo -e "${GREEN}✓ PRE-CHECKS COMPLETED SUCCESSFULLY${NC}"
    echo "=========================================="
    echo "System type: $([ "$ZBM_DETECTED" = true ] && echo "ZFSBootMenu" || echo "Traditional")"
    echo "Updates: ${TOTAL_UPDATES} packages (ZFS: ${ZFS_COUNT}, Kernel: ${KERNEL_COUNT}, Firmware: ${FIRMWARE_COUNT})"
    echo "Backup: $BACKUP_DIR"
    echo "Log: $LOG_FILE"
    echo ""
    echo "Next step: Run zfs-install-updates.sh"
    echo "=========================================="
}

main "$@"